version: 0.2

phases:

  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - npm install -g @angular/cli

  pre_build:
    on-failure: ABORT
    commands:
      - echo Building version ${CODEBUILD_BUILD_NUMBER}
  
  build:
    on-failure: ABORT
    commands:
      - ng build

  post_build:
    on-failure: ABORT
    commands:
      - "echo Build finished"

artifacts:
  files:
    - "**/*"
  base-directory: 'dist/e-commerce-web-app'
  discard-paths: no
